HAPI-397_skeleton
HAPIprotocol/hapi-core pull request #18
Opened 2023-07-07 12:14 UTC by Sergei2404

2023-07-07 12:40 UTC, ars9 requested changes
Please add a `README.md` that would describe how to build and deploy this contract to a test environment.

2023-07-07 12:40 UTC, ars9 commented on near/contract/Cargo.toml
> +license = "GPL-3.0"
Please use the same license as the root of the project: https://github.com/HAPIprotocol/hapi-core/blob/multichain/LICENSE

2023-07-07 12:40 UTC, ars9 commented on near/contract/build_docker.sh
> +if docker ps -a --format '{{.Names}}' | grep -Eq "^${NAME}\$"; then
Please do not create a container like this. A proper docker build should be isolated. I.e. you need to create a Dockerfile that will set up the toolchain and targets, as well as fetch the needed cargo dependencies from the `Cargo.toml` and set up needed environment variables. 

The image would be built with a command like this:
```sh
docker build . -t $IMAGE_NAME
```

After such image is created, we can run it with a command similar to this:

```sh
docker run -it \
  -v $DIR:/builder
  $IMAGE_NAME
```

Please also check, whether we really need this line:
```
--cap-add=SYS_PTRACE --security-opt seccomp=unconfined
```

2023-07-07 12:40 UTC, ars9 commented on near/contract/Cargo.toml
> +name = "hapi-contract"
Please rename the package to "hapi-core-near".

2023-07-11 15:49 UTC, ars9 commented
There's still no information in `README.md` on how to build the contract (we have various scripts and cargo build - which ones to use in which cases?).

2023-07-11 15:51 UTC, ars9 requested changes

2023-07-11 15:51 UTC, ars9 commented on near/Dockerfile
> +LABEL description="Container for build hapi-core-near contract"
As we don't plan to distribute this image, we don't have to label it. And it's self-explanatory in the context.

2023-07-11 15:51 UTC, ars9 commented on near/Dockerfile
> +CMD perl -i -pe 's/\["cdylib", "rlib"\]/\["cdylib"\]/' ./contract/Cargo.toml && \
Do we need `rlib` in `Cargo.toml` at all?

2023-07-11 15:51 UTC, ars9 commented on near/contract/build_docker.sh
> +if docker ps -a --format '{{.Names}}' | grep -Eq "^${NAME}\$"; then
Why do we have "near/build_docker.sh" and "near/contract/build_docker.sh"?

2023-07-12 08:14 UTC, Sergei2404 commented on near/contract/build_docker.sh
> +if docker ps -a --format '{{.Names}}' | grep -Eq "^${NAME}\$"; then
I will delete near/contract/build_docker.sh

2023-07-12 08:18 UTC, Sergei2404 commented on near/Dockerfile
> +CMD perl -i -pe 's/\["cdylib", "rlib"\]/\["cdylib"\]/' ./contract/Cargo.toml && \
Now no, but we will use it for tests

2023-07-12 08:18 UTC, Sergei2404 commented on near/Dockerfile
> +LABEL description="Container for build hapi-core-near contract"
deleted

2023-07-12 09:41 UTC, ars9 approved these changes

2023-07-12 09:42 UTC, merged