Multichain
HAPIprotocol/hapi-core pull request #20
Opened 2023-07-13 09:18 UTC by Sergei2404

2023-07-14 09:10 UTC, ars9 requested changes

2023-07-14 09:10 UTC, ars9 commented on near/contract/tests/utils/execution_extension.rs
> +    fn get_result<T: DeserializeOwned>(self, action: &str) -> T;
Is this a NEAR convention? The method name is very confusing. I'd call it something like `parse` or `deserialize`.

2023-07-14 09:10 UTC, ars9 commented on near/contract/tests/utils/execution_extension.rs
> +    fn get_result<T: DeserializeOwned>(self, action: &str) -> T;
Or maybe `extract`.

2023-07-14 09:10 UTC, ars9 commented on near/contract/tests/configuration/helpers.rs
> +use crate::*;
I'll add that using wildcards for mod reexport is totally fine.

2023-07-14 09:10 UTC, ars9 commented on near/contract/tests/configuration/helpers.rs
> +        "unlock_duration": 60.sec_to_ns(),
Why do we need to store unlock_duration as nanoseconds?

2023-07-14 09:16 UTC, ProstoSergei commented on near/contract/tests/configuration/helpers.rs
> +pub struct StakeAmounts {
Because to use it from contract we need add "rlib" to Cargo.toml, I wrote you this in the last message

2023-07-14 09:17 UTC, ProstoSergei commented on near/contract/tests/errors/mod.rs
> +use crate::*;
Because to use it from contract we need add "rlib" to Cargo.toml, I wrote you this in the last message

2023-07-14 09:20 UTC, ProstoSergei commented on near/contract/tests/utils/execution_extension.rs
> +    fn get_result<T: DeserializeOwned>(self, action: &str) -> T;
No, this extension was written by Ruslan, and I do not change it to keep the same code everywhere

If you want we can change it

2023-07-14 09:22 UTC, ProstoSergei commented on near/contract/tests/configuration/helpers.rs
> +        "unlock_duration": 60.sec_to_ns(),
In doc doesn't specified format of time, so I took most used in Near, but we can easily change it

2023-07-17 07:41 UTC, ars9 commented on near/contract/tests/configuration/helpers.rs
> +pub struct StakeAmounts {
How will you use these types later when we'll create a Rust client implementation for this?

2023-07-17 07:43 UTC, ars9 commented on near/contract/tests/configuration/helpers.rs
> +        "unlock_duration": 60.sec_to_ns(),
These unlock durations will likely be days to weeks. Nanosecond doesn't seem to be an appropriate unit for this.

Also, you did convert it to seconds for some reason here :)

2023-07-17 07:47 UTC, ars9 commented on near/contract/tests/utils/execution_extension.rs
> +    fn get_result<T: DeserializeOwned>(self, action: &str) -> T;
The code right here is open source and we must make it as readable as possible. There's no need to copy code snippets from internal company repos here, if it can be helped.

Personally, for me it's unclear what does this entire module do and I'm sure it could use some refactoring.

2023-07-17 08:52 UTC, ProstoSergei commented on near/contract/tests/configuration/helpers.rs
> +        "unlock_duration": 60.sec_to_ns(),
I didn't convert it to seconds here. I took 60 seconds( just to do simulation faster) and converted it to nanoseconds. I understand that values will be about days. I can do field unlock duration in days, and then convert it to nanoseconds in contract state

2023-07-17 08:57 UTC, ProstoSergei commented on near/contract/tests/utils/execution_extension.rs
> +    fn get_result<T: DeserializeOwned>(self, action: &str) -> T;
Ok, I will rename it to `parse`, it looks good for me

2023-07-17 09:01 UTC, ars9 commented on near/contract/tests/configuration/helpers.rs
> +        "unlock_duration": 60.sec_to_ns(),
Ah, yes, I got it backwards. Let's follow the convention so this value will be displayed as seconds.

2023-07-17 10:09 UTC, ProstoSergei commented on near/contract/tests/configuration/helpers.rs
> +pub struct StakeAmounts {
If it will be outside of this contract folder, so in we will copy paste it to client, or we can create a crate which will store all needed structs, and then include it to projects

2023-07-17 10:15 UTC, ars9 commented on near/contract/tests/configuration/helpers.rs
> +pub struct StakeAmounts {
Deal! Let's proceed with this solution for now then.

2023-07-18 15:19 UTC, merged