Control script
HAPIprotocol/hapi-core pull request #22
Opened 2023-07-17 10:50 UTC by hlgltvnnk

Scripts to operate the contract + test coverage

2023-07-17 11:40 UTC, ars9 requested changes

2023-07-17 11:40 UTC, ars9 commented on client.ts/test/setup.ts
> +    await new Promise((resolve) => setTimeout(resolve, 100));
This feels a bit wonky. Maybe it should be a cycle that actually waits for `lsof` command to return false on this port?

2023-07-17 11:40 UTC, ars9 commented on client.ts/test/setup.ts
> +  await new Promise((resolve) => setTimeout(resolve, 3000));
The timeout value feels arbitrary. Can we try to connect to the validator in a loop until successful here?

2023-07-17 11:40 UTC, ars9 commented on client.ts/test/setup.ts
> +    `cd ../solana && anchor deploy \
Wouldn't this break if we'd run the test not from the `client.ts` directory?

2023-07-17 11:40 UTC, ars9 commented on client.ts/test/setup.ts
> +  await new Promise((resolve) => setTimeout(resolve, 500));
You've used this line so much. Maybe it makese sense to move it to a function like this?

```ts
async function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
```

2023-07-17 11:40 UTC, ars9 commented on client.ts/test/helpers.ts
> +export async function cli_cmd(command: string, arg = "") {
What's the point of separating arguments to a new function argument if you're going to join it later anyway?

2023-07-17 11:40 UTC, ars9 commented on client.ts/test/helpers.ts
> +  toBeEqual = true
The behavior of this function is not very clear from its signature. It looks like if we set `toBeEqual` to false, then it'll expect the values to not be equal (instead of reverting to just "contain").

2023-07-17 11:44 UTC, hlgltvnnk commented on client.ts/test/helpers.ts
> +    pk: "QDWdYo5JWQ96cCEgdBXpL6TVs5whScFSzVbZgobHLrQ",
Changed to "pubkey"

2023-07-17 12:00 UTC, hlgltvnnk commented on client.ts/test/setup.ts
> +var VALIDATOR: ChildProcessWithoutNullStreams;
I need this variable to be mutable (this variable is assigned the value of the validator pid), changed it to let to make it  block-scope

2023-07-17 13:19 UTC, hlgltvnnk commented on client.ts/test/setup.ts
> +  await new Promise((resolve) => setTimeout(resolve, 500));
removed it due to unnecessity

2023-07-17 13:39 UTC, hlgltvnnk commented on client.ts/test/helpers.ts
> +  toBeEqual = true
Replaced toBeEqual argument with enum

2023-07-17 13:59 UTC, hlgltvnnk commented on client.ts/test/setup.ts
> +    `cd ../solana && anchor deploy \
Changed: by retrieving the git top-level directory and using it as base path

2023-07-17 14:25 UTC, ProstoSergei commented on solana/tests/util/setup.ts
> +        "0000000000000000000000000000000000000000000000000000000000000001"
Maybe better do it constant?

2023-07-17 14:35 UTC, hlgltvnnk commented on solana/tests/util/setup.ts
> +        "0000000000000000000000000000000000000000000000000000000000000001"
In some tests, the values of these objects can be changed in accordance with test scenario, so better not to do this

2023-07-17 14:49 UTC, ars9 commented on solana/tests/util/setup.ts
> +        "0000000000000000000000000000000000000000000000000000000000000001"
I think that Sergei meant that the string should be moved to a constant. Which sounds like a good idea to me.

2023-07-18 09:50 UTC, hlgltvnnk commented on client.ts/test/helpers.ts
> +export async function cli_cmd(command: string, arg = "") {
okay, I misunderstood the comment, changed it - joined the argument and the command together in one arg

2023-07-18 11:03 UTC, ProstoSergei approved these changes

2023-07-18 11:27 UTC, ars9 approved these changes

2023-07-18 11:28 UTC, merged