HAPI-469
HAPIprotocol/hapi-core pull request #35
Opened 2023-09-18 18:58 UTC by Sergei2404

2023-09-19 09:30 UTC, ars9 requested changes

2023-09-19 09:30 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +        let signer_account_id = AccountId::try_from(self.account_id.as_ref().unwrap().clone())?;
The compiler will be able to discern the type of this variable from the context below. We also don't want a random unwrap here, so we can replace it by:

```
        let signer_account_id = self
            .account_id
            .as_ref()
            .ok_or(ClientError::SignerError)?
            .clone()
            .try_into()?;
```

2023-09-19 09:30 UTC, ars9 commented on client.rs/src/client/implementations/near/conversion.rs
> +use uuid::Uuid;
Please put the external dependencies above the internal ones.

2023-09-19 09:30 UTC, ars9 commented on client.rs/src/client/implementations/near/conversion.rs
> +use crate::client::result::{ClientError, Result};
Please group crate::client::{} uses into one.

2023-09-19 09:30 UTC, ars9 commented on client.rs/src/client/implementations/near/error.rs
> +use crate::client::result::ClientError;
This file doesn't appear to be used anywhere. Please delete it.

2023-09-19 09:30 UTC, ars9 commented on client.rs/src/client/implementations/near/token.rs
> +use crate::{
Please move create imports below the external ones.

2023-09-19 09:30 UTC, ars9 commented on client.rs/tests/near/setup.rs
> +pub struct Setup {
DO NOT push `test-ledger` directory to the git repository. It should be in `.gitignore`. Please save all the test keys you need separately and copy them as a part of test setup procedure.

2023-09-19 09:30 UTC, ars9 commented on client.rs/tests/near/setup.rs
> +
This newline is not needed.

2023-09-19 09:30 UTC, ars9 commented on client.rs/tests/near/util.rs
> +use std::{net::TcpStream, thread, time::Duration};
Let's put this file to the directory above (i.e. `client.rs/tests/util.rs`), as it's not specific to NEAR.

2023-09-19 09:30 UTC, ars9 commented on near/contract/src/assets/management.rs
> +        let asset_id = format!("{}:{}", address, id.0);
As we use this formatting in several places, let's make it a function (it can be inlined to save on CPU cycles).

2023-09-19 09:30 UTC, ars9 commented on near/contract/src/assets/view.rs
> +// AssetView struct
This comment seems to be redundant.

2023-09-19 09:30 UTC, ars9 commented on near/contract/src/assets/view.rs
> +use crate::{
Please put crate imports below the external ones.

2023-09-19 09:30 UTC, ars9 commented on near/contract/tests/address/helpers.rs
>  pub enum Category {
Why do we need a duplicate of category definition?

2023-09-19 09:37 UTC, ProstoSergei commented on client.rs/Cargo.toml
> +ethers = "=2.0.4"
Conflicts with near libs

2023-09-19 09:47 UTC, ProstoSergei commented on client.rs/src/client/amount.rs
> +impl From<U128> for Amount {
I have "tuple struct constructor `Amount` is private" err

2023-09-19 11:24 UTC, hlgltvnnk commented on client.rs/src/client/implementations/near/client.rs
> +        let rpc_address = "http://localhost:3030";
The rpc address must be obtained from HapiCoreOptions, it is not always a localhost

2023-09-19 11:27 UTC, hlgltvnnk commented on client.rs/src/client/implementations/near/client.rs
> +                gas: 50_000_000_000_000, // 50 TeraGas
Please set this value to a constant

2023-09-19 12:19 UTC, hlgltvnnk requested changes

2023-09-19 12:19 UTC, hlgltvnnk commented on client.rs/src/client/implementations/near/client.rs
> +            .unwrap()
Please replace this unwrap with the corresponding error

2023-09-19 12:19 UTC, hlgltvnnk commented on client.rs/src/client/implementations/near/client.rs
> +            hash: format!("{:?}", tx_hash),
To simplify the code, you can just do tx_hash.to_string()

2023-09-19 12:19 UTC, hlgltvnnk commented on client.rs/src/client/implementations/near/client.rs
> +                account_id: self.contract_address.parse().unwrap(),
Please avoid unwrap - it better to use errors instead

2023-09-19 12:26 UTC, hlgltvnnk requested changes

2023-09-19 12:26 UTC, hlgltvnnk commented on client.rs/src/client/implementations/near/token.rs
> +            client: JsonRpcClient::connect("http://localhost:3030"),
Please extract the rpc address from HapiCoreOptions

2023-09-19 12:26 UTC, hlgltvnnk commented on client.rs/src/client/implementations/near/token.rs
> +            signer: options.private_key.map(|key| key.parse().unwrap()),
Please avoid panic - it is better to hold errors properly

2023-09-19 12:26 UTC, hlgltvnnk commented on client.rs/src/client/implementations/near/token.rs
> +        let tx_hash = self.client.call(request).await?;
You can use macro (or better make it a function) from client.rs to send transactions

2023-09-19 14:10 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +macro_rules! wait_tx_execution {
Only for to not implement this fn for TokenContractNear

2023-09-19 14:34 UTC, ars9 commented on client.rs/src/client/amount.rs
> +impl From<U128> for Amount {
Nevermind, there's already an ethers-specific type imported, we can handle it later as a general refactoring.

2023-09-19 14:35 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +macro_rules! wait_tx_execution {
Can't it be handled by a generic?

2023-09-19 14:38 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +            hash: format!("{:?}", tx_hash),
Not sure if this applicable to NEAR, but ethers does a stupid shortening when to_string is called on an address and transaction hash.

Anyway, this can be written as `format!("{tx_hash:?}")`.

2023-09-20 09:25 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +    fn is_valid_address(&self, address: &str) -> Result<()> {
I can't because it's a fn from HapiCore trait. And this fn do the same thing on evm and Solana

2023-09-20 09:37 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +        // get reporter role
It looks interesting, thx

2023-09-20 12:46 UTC, ProstoSergei commented on near/contract/tests/address/helpers.rs
>  pub enum Category {
Deleted

2023-09-20 13:41 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +        let rpc_address = "http://localhost:3030";
Good catch

2023-09-20 15:14 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +macro_rules! wait_tx_execution {
Done in fn

2023-09-21 07:56 UTC, ars9 requested changes

2023-09-21 07:56 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +pub const PERIOD_CHECK_TX_STATUS: u64 = 2;
It makes sense to create a constant for `Duration`, since we only neede it for that.

2023-09-21 07:56 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +pub(crate) async fn wait_tx_execution(
Let's rename this function to `execute_transaction`, since it doesn't only wait for it, but also executes it.

2023-09-21 07:56 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +        if delta > TRANSACTION_TIMEOUT {
We can define `TRANSACTION_TIMEOUT` as `Duration` and simplify this block to

```rs
if now() > sent_at + TRANSACTION_TIMEOUT {
    return Err(ClientError::TimeoutError("Transaction timeout".to_string()));
}
```

Since `time::Instant::now()` is self-explanatory, I suggest importing it directly.

2023-09-21 07:56 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +            Err(err) => match err.handler_error() {
This can be flattened:

```rs
    Err(err) if matches!(err.handler_error(), Some(methods::tx::RpcTransactionError::UnknownTransaction { .. })) => {
        time::sleep(time::Duration::from_secs(PERIOD_CHECK_TX_STATUS)).await;
        continue;
    }
    Err(err) => {
        Err(err)?
    },
```

2023-09-21 07:56 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +    Ok(Tx {
It occured to me that we can create this impl:

```rs
impl From<&str> for Tx {
    fn from(tx_hash: &str) -> Self {
        Tx {
            hash: tx_hash.to_string(),
        }
    }
}
```

And replace all `Ok(Tx {...})` with `Ok(&tx_hash.into())`. Can you please do this for all implementations?

2023-09-21 07:56 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +        Ok(wait_tx_execution(transaction, signer, &self.client).await?)
Suggestion: since we must use `self.client` with this call, we might as well make this function a method of `self` and omit the `self` argument.

2023-09-21 07:56 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +        let signer_secret_key: SecretKey = signer_secret_key
Can we combine this and previous expressions into one like this?

```rs
let signer_secret_key: SecretKey = self.signer
    .as_ref()
    .ok_or(ClientError::SignerError)?
    .parse()
    .map_err(|_| ClientError::SignerError)?;
```

2023-09-21 07:56 UTC, ars9 commented on client.rs/tests/near/setup.rs
> +use crate::util::wait_for_port;
Let's combine these two `crate` uses into one for cleaner look.

2023-09-21 07:59 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +    fn is_valid_address(&self, address: &str) -> Result<()> {
We'll do this later then.

2023-09-21 09:21 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +        if delta > TRANSACTION_TIMEOUT {
`Instant` is a struct, not a module, so I can't import `time::Instant::now`

2023-09-21 09:37 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +            Err(err) => match err.handler_error() {
It has the same 7 lines, and after formatting it takes 10

2023-09-21 09:46 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +    Ok(Tx {
`tx_hash` it is `CryptoHash`, not `&str.` But we can do `impl from` for it. Since it moved into function and  is used only once, do you think it is still needed?

2023-09-21 09:49 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +        Ok(wait_tx_execution(transaction, signer, &self.client).await?)
It is used by 2 structures, therefore, the option with the method seemed easier to me

2023-09-21 10:35 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +            Err(err) => match err.handler_error() {
The point is not to reduce the number of lines, but to reduce nested complexity. Also, if you properly import `RpcTransactionError` and define `PERIOD_CHECK_TX_STATUS` as a `Duration`, does it still take 10 lines?

I don't insist on this change.

2023-09-21 10:35 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +    Ok(Tx {
It's not *needed*. It's just a more ergonomic way of organizing code. Yes, impl can be created for all necessary types.

2023-09-21 10:44 UTC, ars9 commented on client.rs/src/client/implementations/near/client.rs
> +        Ok(wait_tx_execution(transaction, signer, &self.client).await?)
It doesn't actually differ very much from `fn get_access_key` in this regard. It can be done like this:

```rs
impl HapiCoreNear {
    async fn execute_transaction(
        &self,
        transaction: Transaction,
        signer: InMemorySigner,
    ) -> Result<Tx> {
        ...
        let response = self.client.call(...)
    }
}
```

2023-09-21 10:50 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +            Err(err) => match err.handler_error() {
Yep,  it still take 10 lines

2023-09-21 10:51 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +    Ok(Tx {
So this conversation is resolved?

2023-09-21 10:54 UTC, ProstoSergei commented on client.rs/src/client/implementations/near/client.rs
> +        Ok(wait_tx_execution(transaction, signer, &self.client).await?)
Yes, but also it is used in `TokenContractNear` structure, so I need implement it twice to both structures

2023-09-21 10:57 UTC, merged