HAPI-443
HAPIprotocol/hapi-core pull request #38
Opened 2023-11-15 14:44 UTC by Sergei2404

Added part of indexer for NEAR

2023-11-16 09:34 UTC, ars9 requested changes

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +        let client = client.client.clone();
Why do we need to clone the `contract_address` and `client` on each loop iteration? It sounds expensive.

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +                if block_not_found_flag {
I'm not following the logic behind this flag. Can you please explain it?

If it's trying to detect consecutive missing block to know that it's the latest block on chain, maybe we should just ask the RPC about the current block height before the loop and run a for start..end for it?

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +            sleep(ITERATION_INTERVAL - time_passed).await;
What's `ITERATION_INTERVAL` and why it's handled by NEAR client instead of indexer itself?

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +        block_height += 1;
Doesn't this increment skip the cursor block if placed at the start of the loop body?

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +        if !changes.is_empty() {
This block can be placed inside `match changes_in_block`, which will reduce the amount of branching in the code.

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +        if !changes.is_empty() {
Also can be reduced to

```rust
let timestamp = client
    .call(near_jsonrpc_primitives::types::blocks::RpcBlockRequest {
        block_reference: BlockReference::BlockId(block_id),
    })
    .await?
    .header
    .timestamp_nanosec;

changes
    .iter()
    .map(|change| get_hash_from_cause(&change.cause).expect("no hash"))
    .collect::<HashSet<CryptoHash>>()
    .iter()
    .for_each(|&hash| {
        event_list.push(IndexerJob::TransactionReceipt(NearReceipt {
            hash,
            block_height,
            timestamp,
        }));
    });
```

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +pub(super) async fn process_near_job(
It would be better to instrument this whole function with tracing instead of putting a log message at the start of the function. Also it would be beneficial to log something to identify this particular job. Example:

```rust
#[tracing::instrument(skip(client), fields(receipt_hash = %receipt.hash))]
pub(super) async fn process_near_job(...)
```

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +pub(super) async fn process_near_job(
This has an added benefit of all the tracings inside this function to be in the span of this message, so it's easier to understand what's happening in tracing logs.

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +                .map(|change| get_hash_from_cause(&change.cause).expect("no hash"))
Don't use `expect` to generate a panic where it's not necessary. Think about how we can recover from this error. Can we just ignore a record without a hash? Use filter_map for that. If we can't ignore it, bubble up the error to the function (as it already returns a Result).

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +        get_method_from_receipt(&receipt_view).expect("Err get method_from_receipt");
Same as above. We can just skip this receipt if we can't parse the method name from it, as it is obviously something we're not tracking for.

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +                .expect(format!("Failed to parse method {} tx {}", method, receipt.hash).as_str())
Again, needless panic. We should be able to skip an event if we can't parse it.

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +    Ok(Some(vec![payload]))
Why are we returning a vector with a single item in it?

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +        .expect(format!("Failed to parse {} from {:?}", field, json).as_str())
If this can fail, this function should return a Result<String, ...>.

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +        .expect(format!("Failed to parse id from {:?}", json).as_str());
Same as above, return error, not panic.

2023-11-16 09:34 UTC, ars9 commented on indexer/src/indexer/client/solana.rs
> +        cursor: IndexingCursor::None, // TODO: Implement cursor
What logic are we missing without this TODO?

2023-11-16 12:04 UTC, Sergei2404 commented on indexer/configuration.near.toml
> +log_level = "info"
moved

2023-11-16 12:12 UTC, Sergei2404 commented on indexer/src/indexer/client/near.rs
> +        let client = client.client.clone();
Changed cloning client to use a pointer, `contract_address ` is cloned because it passed in vec, and should be cloned

2023-11-16 12:16 UTC, Sergei2404 commented on indexer/src/indexer/client/near.rs
> +                if block_not_found_flag {
In near testnet is a peculiarity that not all blocks are produced, one block at a random time can be skipped, this part was implemented to avoid this situation on mainnet if it happens.

2023-11-16 12:25 UTC, Sergei2404 commented on indexer/src/indexer/client/near.rs
> +            sleep(ITERATION_INTERVAL - time_passed).await;
In near mainnet nodes is a limit for 600req/min so 60sec/600req = 0,1sec or 100ms, as we have an Iteration interval of 100ms, It was reused. But maybe I will create a separate constant where describe this logic.

2023-11-16 12:33 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +                if block_not_found_flag {
Can't we just do `continue` on the loop if we haven't found the block?

2023-11-16 12:35 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +            sleep(ITERATION_INTERVAL - time_passed).await;
Maybe we should make it configurable for cases when we use private NEAR nodes instead of public ones?

2023-11-16 12:36 UTC, Sergei2404 commented on indexer/src/indexer/client/near.rs
> +                if block_not_found_flag {
I think yes, this option better

2023-11-16 12:40 UTC, Sergei2404 commented on indexer/src/indexer/client/near.rs
> +            sleep(ITERATION_INTERVAL - time_passed).await;
Are we planning to use private nodes for this? If not in the near future, then I think it is not necessary

2023-11-16 15:10 UTC, hlgltvnnk commented on indexer/src/indexer/logic.rs
> +        if let IndexerState::Waiting { .. } = state {
You can avoid additional state checking by moving the logic with a persistent state file to the get_updated_state function

2023-11-16 15:10 UTC, hlgltvnnk commented on indexer/tests/indexer_test.rs
> +        let timer = ITERATION_INTERVAL.saturating_mul(20);
You can make ITERATION_INTERVAL configurable to reduce the wait time in tests

2023-11-16 15:58 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +            sleep(ITERATION_INTERVAL - time_passed).await;
Yes, we do.

2023-11-20 10:02 UTC, Sergei2404 commented on indexer/src/indexer/client/near.rs
> +            sleep(ITERATION_INTERVAL - time_passed).await;
moved it to separate const

2023-11-20 10:08 UTC, Sergei2404 commented on indexer/src/indexer/client/near.rs
> +        block_height += 1;
Yes it is, it was for starting the next block from the last fetched, but I changed now this logic

2023-11-20 11:36 UTC, Sergei2404 commented on indexer/src/indexer/client/near.rs
> +        get_method_from_receipt(&receipt_view).expect("Err get method_from_receipt");
Fixed

2023-11-20 11:38 UTC, Sergei2404 commented on indexer/src/indexer/client/near.rs
> +                .expect(format!("Failed to parse method {} tx {}", method, receipt.hash).as_str())
But why? If a contract call was done, and it changed contract state, and we can’t recognize it, shouldn't we investigate what it was?

2023-11-20 11:41 UTC, Sergei2404 commented on indexer/src/indexer/client/near.rs
> +    Ok(Some(vec![payload]))
Because Indexer is built to work with vectors, but in the near possible get only one tx by request

2023-11-20 13:40 UTC, Sergei2404 commented on indexer/src/indexer/client/solana.rs
> +        cursor: IndexingCursor::None, // TODO: Implement cursor
In current logic cursor takes from a job, so if in `n` fetched blocks last tx was found in an `n-k` block this block will be saved as the cursor, and in the new iteration indexer will be reindex `k` blocks

2023-11-20 13:45 UTC, Sergei2404 commented on indexer/src/indexer/logic.rs
> +        new_cursor: IndexingCursor,
No, because `new_cursor` is used after all jobs are processed

2023-11-20 23:50 UTC, hlgltvnnk commented on indexer/src/indexer/logic.rs
> +        new_cursor: IndexingCursor,
The new cursor should be the last fetched block/transaction, not the last processed one

2023-11-21 00:26 UTC, hlgltvnnk requested changes

2023-11-21 00:26 UTC, hlgltvnnk commented on indexer/src/indexer/logic.rs
> +            return Ok(IndexerState::Processing { cursor });
if i understood correctly, you are passing the last fetched block through processing stage to continue fetching from it in update state, it will be more obvious if you rename "new_cursor" - because that is not new cursor of indexer, but rather "save point", last processed job which is saved in persisted state file

2023-11-21 00:26 UTC, hlgltvnnk commented on indexer/tests/indexer_test.rs
> +        let timer = T::get_fetching_delay().saturating_mul(T::get_fetching_delay_multiplier());
This interval can be universal in tests for all networks - there are no delays caused by pending requests and no need to wait to stay within the limit of rpc, so only value that affects the timer timestamp is amount of batches * fetching delay + waiting timestamp * indexer launches - which is the same for all networks. (also there are no need to create separate method for multiplier)

2023-11-21 08:42 UTC, Sergei2404 commented on indexer/src/indexer/logic.rs
> +        new_cursor: IndexingCursor,
Yes, it is

2023-11-21 08:47 UTC, Sergei2404 commented on indexer/tests/indexer_test.rs
> +        let timer = T::get_fetching_delay().saturating_mul(T::get_fetching_delay_multiplier());
It was done to "make ITERATION_INTERVAL configurable to reduce the wait time in tests

"

2023-11-21 08:52 UTC, Sergei2404 commented on indexer/src/indexer/logic.rs
> +            return Ok(IndexerState::Processing { cursor });
Until it is saved, it is difficult for me to call it a "save_point". This cursor shows until which  block/transaction indexer fetched data

2023-11-21 09:45 UTC, ars9 approved these changes

2023-11-21 09:48 UTC, ars9 commented on indexer/src/indexer/client/near.rs
> +                .expect(format!("Failed to parse method {} tx {}", method, receipt.hash).as_str())
It is not up to near client implementation to decide whether to panic the whole program. This decision must be done on a higher level. If we panic here, the top level indexer cycle doesn't have the option to shutdown gracefully or ignore a known issue.

2023-11-21 11:13 UTC, merged