Explorer graphql schema
HAPIprotocol/hapi-core pull request #43
Opened 2024-01-18 18:50 UTC by hlgltvnnk

2024-01-19 08:40 UTC, ars9 requested changes

2024-01-19 08:40 UTC, ars9 commented on explorer/README.md
> +| --backend     | Network backend type: sepolia, ethereum, bsc, solana, bitcoin, near |
Sepolia, Ethereum and BSC are the same backend type that should be called EVM.

2024-01-19 08:40 UTC, ars9 commented on client.rs/src/client/implementations/solana/conversion.rs
> +        .map_err(|e| ClientError::AssetIdParseError(format!("invalid-asset-id {}", e)))?;
`format!` can be shortened to:
```rs
format!("invalid-asset-id {e}")
```

2024-01-19 15:17 UTC, Sergei2404 requested changes

2024-01-19 15:17 UTC, Sergei2404 commented on explorer/configuration.sample.toml
> +jwt_secret = "my_secret"
Secret should be taken from separate file

2024-01-19 15:17 UTC, Sergei2404 commented on explorer/README.md
> +jwt_secret                          # Secret fro JWT
Secret should be taken from separate file

2024-01-22 09:19 UTC, hlgltvnnk commented on explorer/src/server/handlers/graphql.rs
> +pub(crate) async fn graphiql() -> impl IntoResponse {
this is not a typo - this is the name of extension, i will rename the method to graphiql_playground to avoid misunderstanding

2024-01-25 11:33 UTC, ars9 commented on explorer/src/entity/case/model.rs
> +            query = query.filter(Column::Name.eq(name));
Can we filter with a partial matching for names?

2024-01-25 11:33 UTC, ars9 commented on explorer/src/server/app_server.rs
> +            // TODO: allow access only to the admin
We'll handle this during deployment configuration, there's no need for access control here.

2024-01-25 12:58 UTC, ars9 approved these changes

2024-01-25 13:25 UTC, Sergei2404 approved these changes

2024-01-25 13:57 UTC, merged